Main.cpp
void ShowError(string error)
Referenced by main.
void ListEntityKinds(Project project, string outputFilename)
Referenced by main.
void ListReferenceKinds(Project project, string outputFilename)
Referenced by main.
void ListProjectMetrics(Project project, string outputFilename)
References Project::GetMetrics, Metric::GetName, Metric::GetValue, Metric::IsInteger.
Referenced by main.
void ListEntities(Project project, string outputFilename)
References Project::GetEntities, Entity::GetId, Entity::GetKindText, Reference::GetKindText, Entity::GetName, Entity::GetReferences, Reference::GetTargetEntityId, Reference::GetTargetEntityKindName, Reference::GetTargetEntityName, Entity::GetType.
Referenced by main.
int main(int argc, char *argv[])
References Project::Close, ListEntities, ListEntityKinds, ListProjectMetrics, ListReferenceKinds, Project::Open, ShowError.