ReferenceKindsParser
ReferenceKind ReferenceKindsParser::__referencKind
ReferenceKindsParser::ReferenceKindsParser(string kind, UdbLanguage udbLanguage)
References ParseCppKinds, ParseCSharpKinds, ParseJavaKinds.
ReferenceKindsParser::~ReferenceKindsParser()
void ReferenceKindsParser::ParseCppKinds(string kind)
References StringComparer::ContainsText.
Referenced by ReferenceKindsParser.
void ReferenceKindsParser::ParseCSharpKinds(string kind)
References StringComparer::ContainsText.
Referenced by ReferenceKindsParser.
void ReferenceKindsParser::ParseJavaKinds(string kind)
References StringComparer::ContainsText.
Referenced by ReferenceKindsParser.