Metric
string Metric::_name
Referenced by GetName, Metric.
string Metric::_description
Referenced by GetDescription, Metric.
bool Metric::_isInteger
Referenced by IsInteger, Metric.
double Metric::_value
Referenced by GetValue, Metric.
Metric::Metric(UdbMetric udbMetric, double value)
References _description, _isInteger, _name, _value.
Metric::~Metric()
string Metric::GetName() const
References _name.
Referenced by ListProjectMetrics.
string Metric::GetDescription() const
References _description.
bool Metric::IsInteger() const
References _isInteger.
Referenced by ListProjectMetrics.
double Metric::GetValue() const
References _value.
Referenced by ListProjectMetrics.