EntityKindParser
Scope EntityKindParser::_scope
EntityKind EntityKindParser::_entityKind
EntityKindParser::EntityKindParser(string kind, UdbLanguage udbLanguage)
References ParseCppKinds, ParseCSharpKinds, ParseJavaKinds.
EntityKindParser::~EntityKindParser()
void EntityKindParser::ParseCppKinds(string kind)
References StringComparer::ContainsText.
Referenced by EntityKindParser.
void EntityKindParser::ParseCSharpKinds(string kind)
References StringComparer::ContainsText.
Referenced by EntityKindParser.
void EntityKindParser::ParseJavaKinds(string kind)
References StringComparer::ContainsText.
Referenced by EntityKindParser.