# An example showing how to use the python doxmlparser module to extract some metrics from
# the XML output generated by doxygen for a project.

import sys
from Analysis.Model import Model
from Output.DsiFile import DsiFile


def print_help():
    print('Main <input_directory> <source directory> <model_name> where')
    print('')
    print('input_directory')
    print(' directory containing doxygen xml output')
    print('source_ directory')
    print(' root directory of source files as mentioned in doxygen xml files')
    print('model_name')
    print(' name of model used as base for name output filename')


if __name__ == '__main__':
    print('Arguments count={}'.format(len(sys.argv)))

    for argument in sys.argv:
        print(' argument={}'.format(argument) )

    if len(sys.argv) != 4:
        print_help()
    else:
        input_dir = sys.argv[1]
        src_dir = sys.argv[2]
        model_name = sys.argv[3]

        model = Model(input_dir, src_dir)
        model.build()

        output_file = model_name + '.dsi'
        dsiFile = DsiFile(model.graph, output_file)

        dsiFile.write_to_file()

        print('Dsi file written')


