StringComparer
string StringComparer::_text
Referenced by ContainsText, StringComparer.
StringComparer::StringComparer(string text)
References _text.
StringComparer::~StringComparer()
bool StringComparer::ContainsText(string substring) const
References _text.
Referenced by EntityKindParser::ParseCppKinds, ReferenceKindsParser::ParseCppKinds, EntityKindParser::ParseCSharpKinds, ReferenceKindsParser::ParseCSharpKinds, EntityKindParser::ParseJavaKinds, ReferenceKindsParser::ParseJavaKinds.